name: 'nova_pipe'
version: '1.0.0'
config-version: 2

profile: 'nova_pipe'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nova_pipe:
    +materialized: table